spring:
    datasource:
        url: jdbc:mysql://localhost:3306/clothing-shop?useSSL=true
        username: root
        password:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
            hibernate.enable_lazy_load_no_trans: true
    servlet:
        multipart:
            maxFileSize: 15MB
            maxRequestSize: 15MB

# Handlebars view resolver config
handlebars:
    cache: false
    prefix: /WEB-INF/templates
    suffix: .hbs