spring:
    datasource:
        url: jdbc:mysql://localhost:3306/clothing-shop?useSSL=true
        username: root
        password:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect